version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "media-backend-api-3"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-qw68uixv9n7e"
s3_prefix = "test-app"
region = "eu-west-1"
profile = "media-sam"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DomainName=\"kick-in.media\" HostedZoneId=\"/route53/kick-in.media\""
image_repositories = []
