---
- name: Deploy Docker applications.
  hosts: all

  vars:
    docker_dir: ~/docker_data

  tasks:
    - name: Copy docker-compose file.
      template:
        src: ./docker-compose.yaml.enc
        dest: '{{ docker_dir }}/docker-compose.yaml'

    - name: Pull new image versions.
      command: sudo docker-compose pull
      args:
        chdir: '{{ docker_dir }}'

    - name: Apply docker-compose file.
      command: sudo docker-compose up -d
      args:
        chdir: '{{ docker_dir }}'
