---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Route53 Hosted Zone for kick-in.media'

Parameters:

  DomainName:
    Type: String
    Default: kick-in.media

Resources:

  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref DomainName
    DeletionPolicy: Delete

#  HostedZoneDNSSEC:
#    DependsOn: HostedZoneDNSSECSigningKey # Important! CloudFormation does not wait for the key below by itself...
#    Type: AWS::Route53::DNSSEC
#    Properties:
#      HostedZoneId: !Ref HostedZone
#
#  HostedZoneDNSSECSigningKey:
#    Type: AWS::Route53::KeySigningKey
#    Properties:
#      HostedZoneId: !Ref HostedZone
#      # From the console, can't be fetched from parameter store 'cause region.
#      KeyManagementServiceArn: arn:aws:kms:us-east-1:xxx:key/xxx
#      Name: generic_kms_key
#      Status: ACTIVE

  HostedZoneIdParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/route53/${DomainName}"
      Type: "String"
      Value: !Ref HostedZone
      Description: !Sub "Hosted Zone ID for ${DomainName}"

  CAARecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub "${DomainName}."
      HostedZoneId: !Ref HostedZone
      Type: CAA
      TTL: 300
      ResourceRecords:
        - 0 iodef "mailto:abuse-caa-kickin-media@jonathanj.nl"
        - 0 issue "amazonaws.com"
        - 0 issuewild "amazonaws.com"
        - 0 issue "letsencrypt.org"
        - 0 issuewild "letsencrypt.org"

  # ACM Validation Records
  AcmValidationRecords:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub "_8cade9b0c5c37ed85fb1334e555b09e4.${DomainName}."
      HostedZoneId: !Ref HostedZone
      Type: CNAME
      ResourceRecords:
        - _120c7ca5fe0a3137f32cdc74922dc008.fsdcfjjflr.acm-validations.aws.
      TTL: 300

  # Development Environment
  DevelopmentApi:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub "dev.api.${DomainName}."
      HostedZoneId: !Ref HostedZone
      Type: CNAME
      ResourceRecords:
        - nas.jonathanj.nl
      TTL: 300